import type { Metadata } from "next";
{/*
import { Geist, Geist_Mono } from "next/font/google";
import { Josefin_Sans } from "next/font/google";
import { Comfortaa } from "next/font/google";
*/}
import { Playfair_Display } from "next/font/google";
import "./globals.css";

{/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
})

const comfortaa = Comfortaa({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
  weight: ["400", "700"]
})

*/}

const playfairDisplay = Playfair_Display({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        //className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${playfairDisplay.className}`}
      >
        {children}
      </body>
    </html>
  );
}
